from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from datetime import datetime


def create_docx(contract_title, contract_content, output_path):

    document = Document()

    # -------------------------------
    # Title
    # -------------------------------
    heading = document.add_heading(level=1)
    heading.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    run = heading.add_run(contract_title)
    run.bold = True
    run.font.size = Pt(20)

    # -------------------------------
    # Subtitle
    # -------------------------------
    subtitle = document.add_paragraph()
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle.add_run(
        f"Generated by AccordAI\n{datetime.now().strftime('%d %B %Y')}"
    ).italic = True

    document.add_paragraph()

    # -------------------------------
    # Contract Body
    # -------------------------------
    body = document.add_paragraph()

    body.style.font.name = "Times New Roman"
    body.style.font.size = Pt(12)

    body.add_run(contract_content)

    document.add_page_break()

    # -------------------------------
    # Signature Section
    # -------------------------------
    document.add_heading("Signatures", level=2)

    document.add_paragraph()

    document.add_paragraph(
        "Party A Signature: __________________________"
    )

    document.add_paragraph()

    document.add_paragraph(
        "Party B Signature: __________________________"
    )

    document.add_paragraph()

    document.add_paragraph(
        "Date: __________________"
    )

    document.save(output_path)